# Generated by Django 5.1.3 on 2024-12-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_customuser_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='manager',
        ),
    ]
