# Generated by Django 5.1.3 on 2024-12-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_remove_customuser_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='employee', max_length=10),
        ),
    ]
