# Generated by Django 5.1.3 on 2024-12-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_alter_leavetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(default=True, max_length=250, null=True),
        ),
    ]
