# Generated by Django 4.2.7 on 2024-12-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='manager',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
