# Generated by Django 5.1.3 on 2024-12-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_alter_customuser_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='document',
            new_name='attachment',
        ),
    ]
