# Generated by Django 5.1.3 on 2024-12-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_alter_leaverequest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachment/'),
        ),
    ]
