# Generated by Django 5.1.3 on 2024-12-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_customuser_profile_alter_leaverequest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
