# Generated by Django 5.1.3 on 2024-12-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_rename_comments_leaverequest_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['-id']},
        ),
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
    ]
